# A simple random generator is obtained by the formula:
# rNew = (a ⋅ rOld + b) % m
# and then setting rNew to rOld. Write a program that asks the user to enter an initial value
# for rOld. (Such a value is often called a seed). Then print the first 100 random integers
# generated by this formula, using a = 32310901, b = 1729 e m = 224
# . [P4.27]

rOld = int(input("Enter initial value: "))
a = 32310901
b = 1729
m = 224

for i in range (0, 100, 1):
    rOld = (a * rOld + b) % m
    print(rOld, end=" ")

